---
- hosts: test
  become: yes
  vars:
      username: user
  tasks:
  - name: create .ssh folder
    file:
      path: /home/{{ username }}/.ssh
      state: directory
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: 0700
  - name: copy authorized_keys file
    copy:
      src: /path/to/authorized_keys
      dest: /home/{{ userame }}/.ssh/authorized_keys
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: 0600
