---
- hosts: test
  become: yes
  tasks:
  - name: create .ssh folder
    file:
      path: /home/orionnet/adm-exttombe/.ssh
      state: directory
      owner: adm-exttombe
      group: "domain users"
      mode: 0700
  - name: copy authorized_keys file
    copy:
      src: /home/fitombedn/orion/ldap/authorized_keys
      dest: /home/orionnet/adm-exttombe/.ssh/authorized_keys
      owner: adm-exttombe
      group: "domain users"
      mode: 0600
