---
# configure sssd and kerberos for AD integration
- hosts: test
  remote_user: fitombedn
  become: yes
  become_method: sudo
  tasks:
      - name: check current sssd configuration 
        shell: cat /etc/sysconfig/authconfig
        register: authconf_content
        #RHEL 6
      - block:
          - name: copy krb5.conf RHEL6
            copy:
                src: /home/fitombedn/orion/ldap/6krb5.conf
                dest: /etc/krb5.conf
                owner: root
                group: root
                mode: 0644
            notify:
                #- clear sssd_cache
                - restart sssd6
          - name: copy sssd.conf RHEL6
            copy:
                src: /home/fitombedn/orion/ldap/6sssd.conf
                dest: /etc/sssd/sssd.conf
                owner: root
                group: root
                mode: 0600
            notify:
                #- clear sssd_cache
                - restart sssd6
          - name: copy nsswitch.conf RHEL6
            copy:
                src: /home/fitombedn/orion/ldap/6nsswitch.conf
                dest: /etc/nsswitch.conf
                owner: root
                group: root
                mode: 0644
          - name: messagebus start & enable RHEL6
            service: name=messagebus state=started enabled=True
        when: 
            - ansible_os_family == "RedHat" 
            - ansible_distribution_major_version == "6"
        #RHEL 7
      - block:
          - name: copy sssd.conf RHEL7
            copy:
                src: /home/fitombedn/orion/ldap/7sssd.conf
                dest: /etc/sssd/sssd.conf
                owner: root
                group: root
                mode: 0600
            notify:
                #- clear sssd_cache
                - restart sssd7
          - name: copy nsswitch.conf RHEL7
            copy:
                src: /home/fitombedn/orion/ldap/7nsswitch.conf
                dest: /etc/nsswitch.conf
                owner: root
                group: root
                mode: 0644
        when:
            - ansible_os_family == "RedHat"
            - ansible_distribution_major_version == "7"
        #authconfig for all versions
      - name: authconfig to use sssd 
        command: /usr/sbin/authconfig --enablesssd --enablesssdauth --update
        #execute only when sssd usage is not configured yet
        when: 
            - authconf_content.stdout.find('USESSSDAUTH=no') != -1
            - authconf_content.stdout.find('USESSSD=no') != -1
      - name: authconfig homedir 
        command: /usr/sbin/authconfig --enablemkhomedir --update
        when: 
            - authconf_content.stdout.find('USEMKHOMEDIR=no') != -1
        #now start $ enable sssd depending on release
      - name: sssd start & enable RHEL6
        service: name=sssd state=started enabled=True
        when: 
            - ansible_os_family == "RedHat" 
            - ansible_distribution_major_version == "6"
      - name: start & enable sssd RHEL7
        systemd: name=sssd state=started enabled=True
        when:
            - ansible_os_family == "RedHat"
            - ansible_distribution_major_version == "7"
  handlers:
      - name: clear sssd_cache
        command: /usr/sbin/sss_cache -E
        when: 
            - authconf_content.stdout.find('USESSSDAUTH=yes') != -1
            - authconf_content.stdout.find('USESSSD=yes') != -1
      - name: restart sssd6
        service: name=sssd state=restarted
      - name: restart sssd7
        systemd: name=sssd state=restarted 
